// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "KT_GiGA_2G_F644"
#define SECRET_PASS "6xd70xh686"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "afuml1qfr8u7t-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIChjCCAW6gAwIBAgIVAJo40B3XNcFm+4o2OJs36+jG7YCgMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMDEyMTEwNDE4
MjNaFw00OTEyMzEyMzU5NTlaMBUxEzARBgNVBAMTCkV4aXREZXZpY2UwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAAQDbo7qC8nleAoubINxPDaKOWdwagMkkZBfguRI
JWBWS6+LxqeCJUyGvn9QMpbukYsSsGXMjTT1PNIwyDHWgb/2o2AwXjAfBgNVHSME
GDAWgBSyapfCIhthZgX0yS4Qrx/APjX+8DAdBgNVHQ4EFgQUyDhgzl0r805DNorW
CCfDVKGwqGwwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN
AQELBQADggEBAAnCC/oRCF5qiU2pXFRH/I9swhFYotK7Yo1Y8UiTLw4nyTRQNnTs
KojHMHyhTollUmz8Iz01OHHGvGhYuB/Qhgcwc0NyYE9KkJYQVs57EHpAbDyYX51I
Zn5RUxh81t1ihkiYc//O1ON/aQF2AVNwmvRSft8p7+An36VEQfHe/OlnsuodgZy2
7HdfhoBaDXVl2uPc0O4XSgYg99qDZXg8MU1HQqLaXT0c33+LKzYqynqdY2aQvtpE
XY0TkqF1B90FQTAziqA5hrrzM6uOBnn9diNopENkwxabRRb1ObCvNEkuYGjLKVWx
U/ZJoEaJxWsNKt01dMISC7sbtZsEt3ftr80=
-----END CERTIFICATE-----
)";
